# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/FalconSocial/pre-commit-python-sorter
    sha: master
    hooks:
      - id: python-import-sorter
        args: ["--silent-overwrite"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: flake8

  - repo: https://github.com/ambv/black
    rev: origin/stable
    hooks:
      - id: black
        args: [--line-length=79, --target-version=py38]
        python_version: python3.8
