# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
files: "mmvb_backend/"

repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.3.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=79, --target-version=py38]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
