version: '3'

services:
  backend:
    restart: unless-stopped
    build: .
    entrypoint: /usr/src/app/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mysql
    environment:
      MMVB_SERVER_URL: http://backend
      DB_HOST: mysql
      REDIS_HOST: redis
      WAIT_HOSTS: mysql:3306, redis:6379
      # URL will be added to CORS_WHITELIST
      WEBAPP_HOST_URL: ${WEBAPP_HOST_URL}

  celery:
    restart: unless-stopped
    build: ./
    command: sh -c "/wait && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery worker -A mmvb_backend -l info"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - mysql
    environment:
      MMVB_SERVER_URL: http://backend
      DB_HOST: mysql
      REDIS_HOST: redis
      WAIT_HOSTS: mysql:3306, redis:6379, backend:8000
      WAIT_HOSTS_TIMEOUT: 60
      # URL will be added to CORS_WHITELIST
      WEBAPP_HOST_URL: ${WEBAPP_HOST_URL}

  redis:
    restart: unless-stopped
    image: redis:alpine
    sysctls:
      net.core.somaxconn: '511'
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"

  mysql:
    restart: unless-stopped
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'mmvb'
      MYSQL_ROOT_PASSWORD: 'rootsecret'
      MYSQL_USER: 'system'
      MYSQL_PASSWORD: 'systemsecret'

volumes:
  mysql: