
# This is a component of the MMVB for the "Symptom assessment" sub-group
# (of the the International Telecommunication Union focus group
# "Artificial Intelligence for Health".
# For copyright and licence, see the parent directory. 

swagger: '2.0'
info:
  version: 0.0.1
  title: 'ITU/WHO AI Symptom Checker App Sub-group MMVB'
  description: "Interface to create synthetic cases for the minimal minimal viable benchmark (MMVB)."
consumes:
  - application/json
produces:
  - application/json
basePath: /case-generator/v1


paths:
  /generate-case:
    get:
      description: Generates a synthetic patient cases for the MMVB.
      operationId: api.generate_case
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Result"
        500:
          description: Error response
          schema:
            $ref: "#/definitions/Error"


definitions:
  Result:
    properties:
      caseData:
        properties:
          caseId:
            type: string
            description: unique id of the cases
            example: xyz321
          metaData:
            type: object
            description: meta data for the case
          profileInformation:
            properties:
              biologicalSex:
                type: string
                description: biological sex of a patient (male or female for the MMVB)
                example: female
              age:
                type: number
                description: age of a patient
                example: 25
            required:
              - biologicalSex
              - age
          presentingComplaints:
            type: array
            items:
              $ref: "#/definitions/ComplaintPiece"
          otherFeatures:
            type: array
            items:
              $ref: "#/definitions/ComplaintPiece"
        required:
          - caseId
          - metaData
          - profileInformation
          - presentingComplaints
          - otherFeatures
      valuesToPredict:
        description: ground gruth or other data to test against
        properties:
          expectedTriageLevel:
            type: string
            description: expected triage level (SC for self-care, PC for primary care, EC for emergency care)
            example: "PC"
          condition:
            properties:
              id:
                type: string
                description: id of the condition
                example: "abc123"
              name:
                type: string
                description: name of the condition
                example: "Ectopic Pregnancy"
            required:
              - id
              - name
        required:
          - expectedTriageLevel
          - condition
    required:
      - caseData
      - valuesToPredict
  ComplaintPiece:
    properties:
      id:
        type: string
        description: id of the concept
        example: "abc123"
      name:
        type: string
        description: name of the concept
        example: "Abdominal pain"
      state:
        type: string
        description: state of the concept (can be present, absent, unsure)
        example: "present"
    required:
      - id
      - name
      - state
  Error:
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
